export const ICON_NAMES = {
  ARROW_DOWN: 'arrow down',
  ARROW_LEFT: 'arrow left',
  ARROW_RIGHT: 'arrow right',
  ARROW_UP: 'arrow up',
  BARS: 'bars',
  BATHROOM: 'bathroom',
  BEDROOM_DOOR: 'bedroom door',
  BUS: 'bus',
  CALENDAR: 'calendar',
  CARET_DOWN: 'caret down',
  CARET_LEFT: 'caret left',
  CARET_RIGHT: 'caret right',
  CARET_UP: 'caret up',
  CHECK_IN: 'check in',
  CHECK_OUT: 'check out',
  CHECKMARK: 'checkmark',
  CHEVRON_LEFT: 'chevron left',
  CHEVRON_RIGHT: 'chevron right',
  CLOCK: 'clock',
  CLOSE: 'close',
  COFFEE: 'coffee',
  DOUBLE_BED: 'double bed',
  FACEBOOK: 'facebook',
  FIRE: 'fire',
  GOOGLE_PLUS: 'google plus',
  GUESTS: 'guests',
  HOME: 'home',
  INFO: 'info',
  INSTAGRAM: 'instagram',
  LEAF: 'leaf',
  LOCATION: 'location',
  MAP_PIN: 'map pin',
  PAW: 'paw',
  PHONE: 'phone',
  PINTEREST: 'pinterest',
  PLACEHOLDER: 'placeholder',
  PLANE: 'plane',
  QUESTION_MARK: 'question mark',
  ROAD: 'road',
  SEARCH: 'search',
  SINGLE_BED: 'single bed',
  STAR: 'star',
  SQUARE: 'square',
  SUN: 'sun',
  TRAIN: 'train',
  TWITTER: 'twitter',
  USERS: 'users',
  WHEELCHAIR: 'wheelchair',
  YOUTUBE: 'youtube',
};

export const ICON_NAMES_LIST = Object.values(ICON_NAMES);
