const THEME_CUSTOM_PROPERTY_PREFIX = '--lodgify-ui';

export const THEME_CUSTOM_PROPERTY_IDENTIFIERS = {
  ACTION_COLOR: `${THEME_CUSTOM_PROPERTY_PREFIX}-action-color`,
  ACTION_DARKER_COLOR: `${THEME_CUSTOM_PROPERTY_PREFIX}-action-darker-color`,
  ACTION_LIGHTER_COLOR: `${THEME_CUSTOM_PROPERTY_PREFIX}-action-lighter-color`,
  ACTION_CONTRAST_COLOR: `${THEME_CUSTOM_PROPERTY_PREFIX}-action-contrast-color`,

  LINK_COLOR: `${THEME_CUSTOM_PROPERTY_PREFIX}-link-color`,
  LINK_DARKER_COLOR: `${THEME_CUSTOM_PROPERTY_PREFIX}-link-darker-color`,

  BODY_FONT: `${THEME_CUSTOM_PROPERTY_PREFIX}-body-font`,
  HEADING_FONT: `${THEME_CUSTOM_PROPERTY_PREFIX}-heading-font`,
  TITLE_FONT: `${THEME_CUSTOM_PROPERTY_PREFIX}-title-font`,
  SUB_TITLE_FONT: `${THEME_CUSTOM_PROPERTY_PREFIX}-subtitle-font`,
};
