const THEME_CUSTOM_PROPERTY_PREFIX = '--lodgify-ui';

export const THEME_CUSTOM_PROPERTY_IDENTIFIERS = {
  LINK_COLOR: `${THEME_CUSTOM_PROPERTY_PREFIX}-link-color`,
  LINK_HOVER_COLOR: `${THEME_CUSTOM_PROPERTY_PREFIX}-link-hover-color`,
};
